---
output:
  html_document:
title: "Исследование возможностей автоматизации сбора данных о доменах"
---
# Цель работы:
Собрать информацию о 15 доменах в категории [Graphics](https://www.alexa.com/topsites/category/Top/Computers/Graphics)

# Используемое ПО:

1. `Rstudio IDE`
2. `whois`
3. `nmap`
4. `dig`


# Данные которые нужно собрать:

1. `Домен`
2. `IP`
3. `IP Netblock`
3. `Страна, город`
4. `Адрес`
5. `Телефон`
6. `Хостинг (при наличии)`
7. `Открытые порты`


# Таблица со значениями:

```{r, echo=FALSE, message=FALSE}
library(tidyverse)

get_sum_df <- function(company_url) {
  country_state <- NA
  dig <- system2('dig', company_url, stdout = TRUE)
  ip <- dig %>%
    grep(pattern = company_url, value = TRUE) %>%
    str_extract(pattern = "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b")
  ip <- ip[!is.na(ip)]
  
  whois <- system2('whois', ip[1], stdout = TRUE)
  phones <- whois %>%
    grep(pattern = "Phone", value = TRUE, ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ") %>%
    data.table::transpose() %>%
    .[[2]] %>%
    unique() %>%
    str_c(collapse = " ")
  if(length(phones)==0) phones <- NA
  
  netblock <- whois %>%
    grep(pattern = "CIDR", value = TRUE, ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1] %>%
    str_c(collapse = " ")
  if(length(netblock)==0) netblock <- NA
  
  country <- whois %>%
    grep(pattern = "Country",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1]
  if(length(country)==0) country <- NA
  
  country_state <- whois %>%
    grep(pattern = "State",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1]
  if(length(country_state)==0) country_state <- NA
  
  address <- whois %>%
    grep(pattern = "address",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1] %>%
    str_c(collapse = " ")
  if(length(address)==0) address <- NA
  
  hosting <- whois %>%
    grep(pattern = "Hosting",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ")
  hosting <- lapply(hosting, collapse = " ", str_c) %>%
    str_c(collapse = " ")
  if(length(hosting)==0) hosting <- NA
  
  nmap <-
    system2('nmap',
            args = c('-p', '22,21,80,443', ip[1]),
            stdout = TRUE)
  ports <- nmap %>%
    grep(pattern = "open",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ") %>%
    data.table::transpose() %>%
    .[[1]] %>%
    str_c(collapse = " ")
  ip <- str_c(ip,collapse = ' ')

  company_sum <-
    data.frame(
      csum = c(
        company_url,
        ip,
        netblock,
        country,
        country_state,
        address,
        phones,
        hosting,
        ports
      ),
      row.names = c(
        'company_url',
        'ip',
        'netblock',
        'country',
        'country_state',
        'address',
        'phones',
        'hosting',
        'ports'
      )
    )
  company_sum
  
}
```


```{r, echo=FALSE}

urls <- c("Fontshop.com","Peachpit.com","Iconsdb.com","Linotype.com","Monotype.com","Clker.com","Elated.com","Dryicons.com","Pixabay.com", "Flaticon.com", "Dafont.com", "Fontsquirrel.com", "1001freefonts.com", "Thenounproject.com", "Fontlibrary.org")
dfs <- lapply(urls, get_sum_df) 
result <- bind_cols(dfs)

row.names(result) <- c('company_url',
        'ip',
        'netblock',
        'country',
        'country_state',
        'address',
        'phones',
        'hosting',
        'ports'
      )


colnames(result) <- map(result[1,],as.character) %>% unlist()
result <- result[-1,]
knitr::kable(result)
```

# Используемые web-технологии:

```{r cache=TRUE, echo=FALSE}
library(rappalyzer)
rappalyze("Fontshop.com")
rappalyze("Peachpit.com")
rappalyze("Iconsdb.com")
rappalyze("Linotype.com")
rappalyze("Monotype.com")
rappalyze("Clker.com")
rappalyze("Elated.com")
rappalyze("Dryicon")
rappalyze("Pixabay.com")
rappalyze("Flaticon.com")
rappalyze("Dafont.com")
rappalyze("Fontsquirrel.com")
rappalyze("1001freefonts.com")
rappalyze("Thenounproject.com")
rappalyze("Fontlibrary.org")
```

